# golangci-lint configuration for goapps-backend
# https://golangci-lint.run/usage/configuration/
# Compatible with golangci-lint v2.3.0+ (GitHub Actions)

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

# Formatters (separate from linters in v2)
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/mutugading/goapps-backend

linters:
  enable:
    # Core linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - dupl
    - errname
    - errorlint
    - exhaustive
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
    gocyclo:
      min-complexity: 15
    gocognit:
      min-complexity: 20
    dupl:
      threshold: 150
    goconst:
      min-len: 3
      min-occurrences: 3
    godot:
      scope: declarations
      capital: true
    gosec:
      excludes:
        - G104
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst
          - gocognit
      - path: gen/
        linters:
          - all
      - path: config\.go$
        linters:
          - lll

output:
  formats:
    text:
      path: stdout
      colors: true
