package postgres

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/mutugading/goapps-backend/services/finance/internal/domain/costcalc"
	"github.com/mutugading/goapps-backend/services/finance/pkg/safeconv"
)

// CostCalcJobRepository persists calc Job aggregates against `cal_job`.
type CostCalcJobRepository struct {
	db *DB
}

// NewCostCalcJobRepository constructs a CostCalcJobRepository.
func NewCostCalcJobRepository(db *DB) *CostCalcJobRepository {
	return &CostCalcJobRepository{db: db}
}

var _ costcalc.JobRepository = (*CostCalcJobRepository)(nil)

// Create inserts a new QUEUED job. The job code is generated by
// `generate_cal_job_code()` server-side in the same statement so the JOB-YYYYMM-NNNN
// counter and the new row remain consistent.
func (r *CostCalcJobRepository) Create(ctx context.Context, j *costcalc.Job) error {
	if j == nil {
		return fmt.Errorf("create cal job: nil job")
	}
	const q = `
		INSERT INTO cal_job (
			cj_job_code, cj_period, cj_calculation_type, cj_scope, cj_product_filter,
			cj_status, cj_priority, cj_triggered_by, cj_created_by
		) VALUES (generate_cal_job_code(), $1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING cj_job_id, cj_job_code`
	var (
		id   int64
		code string
	)
	err := r.db.QueryRowContext(ctx, q,
		j.Period(), string(j.CalcType()), string(j.Scope()), nullableJSON(j.ProductFilter()),
		string(j.Status()), safeconv.IntToInt32(j.Priority()), j.TriggeredBy(), j.CreatedBy(),
	).Scan(&id, &code)
	if err != nil {
		return fmt.Errorf("insert cal job: %w", err)
	}
	j.AssignID(id, code)
	return nil
}

// GetByID returns a hydrated Job or ErrJobNotFound.
func (r *CostCalcJobRepository) GetByID(ctx context.Context, id int64) (*costcalc.Job, error) {
	const q = `
		SELECT cj_job_id, cj_job_code, cj_period, cj_calculation_type, cj_scope,
		       cj_product_filter, cj_status, cj_priority,
		       cj_total_products, cj_total_chunks, cj_total_waves, cj_processed_chunks,
		       cj_success_count, cj_failed_count, cj_blocked_count, cj_error_summary,
		       cj_triggered_by, cj_queued_at, cj_started_at, cj_completed_at,
		       COALESCE(cj_duration_ms, 0), cj_created_by
		FROM cal_job
		WHERE cj_job_id = $1`
	job, err := scanJob(r.db.QueryRowContext(ctx, q, id))
	if errors.Is(err, sql.ErrNoRows) {
		return nil, costcalc.ErrJobNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get cal job: %w", err)
	}
	return job, nil
}

// List applies optional filters with pagination.
func (r *CostCalcJobRepository) List(ctx context.Context, f costcalc.JobFilter) ([]*costcalc.Job, int, error) {
	where, args := buildJobListWhere(f)
	whereSQL := ""
	if len(where) > 0 {
		whereSQL = " WHERE " + strings.Join(where, " AND ")
	}

	var total int
	if err := r.db.QueryRowContext(ctx, `SELECT count(*) FROM cal_job`+whereSQL, args...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("count cal jobs: %w", err)
	}

	page := f.Page
	if page < 1 {
		page = 1
	}
	pageSize := f.PageSize
	if pageSize < 1 {
		pageSize = 20
	}
	if pageSize > 200 {
		pageSize = 200
	}
	offset := (page - 1) * pageSize

	listSQL := `
		SELECT cj_job_id, cj_job_code, cj_period, cj_calculation_type, cj_scope,
		       cj_product_filter, cj_status, cj_priority,
		       cj_total_products, cj_total_chunks, cj_total_waves, cj_processed_chunks,
		       cj_success_count, cj_failed_count, cj_blocked_count, cj_error_summary,
		       cj_triggered_by, cj_queued_at, cj_started_at, cj_completed_at,
		       COALESCE(cj_duration_ms, 0), cj_created_by
		FROM cal_job` + whereSQL + ` ORDER BY cj_created_at DESC` +
		fmt.Sprintf(" LIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	args = append(args, pageSize, offset)

	rows, err := r.db.QueryContext(ctx, listSQL, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("list cal jobs: %w", err)
	}
	defer closeRows(rows)

	out := []*costcalc.Job{}
	for rows.Next() {
		job, scanErr := scanJob(rows)
		if scanErr != nil {
			return nil, 0, fmt.Errorf("scan cal job row: %w", scanErr)
		}
		out = append(out, job)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("iterate cal job rows: %w", err)
	}
	return out, total, nil
}

// UpdateStatus rewrites only the status column.
func (r *CostCalcJobRepository) UpdateStatus(ctx context.Context, id int64, status costcalc.JobStatus) error {
	return r.execUpdate(ctx,
		`UPDATE cal_job SET cj_status = $1 WHERE cj_job_id = $2`,
		string(status), id,
	)
}

// UpdateTotals records planning output.
func (r *CostCalcJobRepository) UpdateTotals(ctx context.Context, id int64, total, totalChunks, totalWaves int) error {
	return r.execUpdate(ctx,
		`UPDATE cal_job
		    SET cj_total_products = $1, cj_total_chunks = $2, cj_total_waves = $3
		  WHERE cj_job_id = $4`,
		safeconv.IntToInt32(total), safeconv.IntToInt32(totalChunks), safeconv.IntToInt32(totalWaves), id,
	)
}

// UpdateProgress records mid-flight counters.
func (r *CostCalcJobRepository) UpdateProgress(ctx context.Context, id int64, processed, succ, fail, blocked int) error {
	return r.execUpdate(ctx,
		`UPDATE cal_job
		    SET cj_processed_chunks = $1, cj_success_count = $2,
		        cj_failed_count = $3, cj_blocked_count = $4
		  WHERE cj_job_id = $5`,
		safeconv.IntToInt32(processed), safeconv.IntToInt32(succ),
		safeconv.IntToInt32(fail), safeconv.IntToInt32(blocked), id,
	)
}

// UpdateCompletion records final outcome counts and duration.
func (r *CostCalcJobRepository) UpdateCompletion(
	ctx context.Context, id int64, status costcalc.JobStatus,
	succ, fail, blocked int, durationMs int64, errSummary []byte,
) error {
	return r.execUpdate(ctx,
		`UPDATE cal_job
		    SET cj_status = $1, cj_success_count = $2, cj_failed_count = $3, cj_blocked_count = $4,
		        cj_completed_at = now(), cj_duration_ms = $5, cj_error_summary = $6
		  WHERE cj_job_id = $7`,
		string(status), safeconv.IntToInt32(succ), safeconv.IntToInt32(fail), safeconv.IntToInt32(blocked),
		durationMs, nullableJSON(errSummary), id,
	)
}

// execUpdate runs a parameterized UPDATE and maps zero rows affected to ErrJobNotFound.
func (r *CostCalcJobRepository) execUpdate(ctx context.Context, q string, args ...any) error {
	res, err := r.db.ExecContext(ctx, q, args...)
	if err != nil {
		return fmt.Errorf("update cal job: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("update cal job rows: %w", err)
	}
	if n == 0 {
		return costcalc.ErrJobNotFound
	}
	return nil
}

// rowScanner is the minimal interface satisfied by *sql.Row and *sql.Rows.
type rowScanner interface {
	Scan(dest ...any) error
}

// scanJob reads one job row and returns a hydrated domain Job.
func scanJob(s rowScanner) (*costcalc.Job, error) {
	var (
		id              int64
		code, period    string
		calcType, scope string
		filter          []byte
		status          string
		priority        int32
		total, tc, tw   int32
		processed       int32
		succ, fail, blk int32
		errSummary      []byte
		triggeredBy     string
		queuedAt        time.Time
		startedAt       sql.NullTime
		completedAt     sql.NullTime
		durationMs      int64
		createdBy       string
	)
	if err := s.Scan(
		&id, &code, &period, &calcType, &scope, &filter, &status, &priority,
		&total, &tc, &tw, &processed, &succ, &fail, &blk, &errSummary,
		&triggeredBy, &queuedAt, &startedAt, &completedAt, &durationMs, &createdBy,
	); err != nil {
		return nil, err
	}
	var startedPtr, completedPtr *time.Time
	if startedAt.Valid {
		t := startedAt.Time
		startedPtr = &t
	}
	if completedAt.Valid {
		t := completedAt.Time
		completedPtr = &t
	}
	return costcalc.HydrateJob(
		id, code, period, costcalc.CalculationType(calcType), costcalc.JobScope(scope), filter,
		costcalc.JobStatus(status), int(priority), int(total), int(tc), int(tw),
		int(processed), int(succ), int(fail), int(blk), errSummary, triggeredBy,
		queuedAt, startedPtr, completedPtr, durationMs, createdBy,
	), nil
}

// buildJobListWhere translates a JobFilter into WHERE clauses + positional args.
func buildJobListWhere(f costcalc.JobFilter) ([]string, []any) {
	where := []string{}
	args := []any{}
	idx := 1
	if f.Period != "" {
		where = append(where, fmt.Sprintf("cj_period = $%d", idx))
		args = append(args, f.Period)
		idx++
	}
	if f.CalcType != "" {
		where = append(where, fmt.Sprintf("cj_calculation_type = $%d", idx))
		args = append(args, string(f.CalcType))
		idx++
	}
	if f.Status != "" {
		where = append(where, fmt.Sprintf("cj_status = $%d", idx))
		args = append(args, string(f.Status))
		idx++
	}
	if f.TriggeredBy != "" {
		where = append(where, fmt.Sprintf("cj_triggered_by = $%d", idx))
		args = append(args, f.TriggeredBy)
	}
	return where, args
}

// nullableJSON returns nil for empty []byte (so the driver writes NULL into
// JSONB columns) and the original slice otherwise. Empty []byte is rejected by
// lib/pq as invalid JSON syntax.
func nullableJSON(b []byte) any {
	if len(b) == 0 {
		return nil
	}
	return b
}
