// Package postgres provides PostgreSQL implementations for domain repositories.
package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"strconv"

	"github.com/google/uuid"

	"github.com/mutugading/goapps-backend/services/finance/internal/domain/costproductparameter"
	"github.com/mutugading/goapps-backend/services/finance/internal/domain/costroute"
	"github.com/mutugading/goapps-backend/services/finance/internal/domain/mbcomposition"
	"github.com/mutugading/goapps-backend/services/finance/internal/domain/mbhead"
)

// mbCostProductTypeCode is the cost_product_type.cpt_type_code seeded (migration 000450) for
// auto-generated MB recipe products.
const mbCostProductTypeCode = "MB"

// mbCostProductSource marks cost_product_master rows auto-generated by the MB recipe workflow
// (never manually created), matching migration 000449's cpm_source column comment.
const mbCostProductSource = "MB_RECIPE"

// mst_parameter codes frozen onto an auto-generated MB cost product at Validate time, per design
// addendum §10.2 step 5. Order matches display_order in migration 000444.
const (
	paramMBWaste           = "MB_WASTE"
	paramMBQualityLoss     = "MB_QUALITY_LOSS"
	paramMBEfficiency      = "MB_EFFICIENCY"
	paramMBDevExpense      = "MB_DEV_EXPENSE"
	paramMBPacking         = "MB_PACKING"
	paramMBProdPerDay      = "MB_PROD_PER_DAY"
	paramMBThroughput      = "MB_THROUGHPUT"
	paramMBNoProcess       = "MB_NO_PROCESS"
	paramIsBoughtout       = "IS_BOUGHTOUT"
	paramMachineFixedTotal = "MACHINE_MB_FIXED_TOTAL"
	paramCompositionVer    = "MB_COMPOSITION_VERSION"
)

// mst_mb_param picklist codes whose frozen mbh_param_throughput_per_hour/mbh_param_no_of_process
// values are option codes (e.g. "B"), not numeric magnitudes — the numeric value lives on
// mst_mb_param_option and must be resolved before freezing onto CPP (data_type NUMBER).
const (
	mbpCodeThroughputPerHour = "THROUGHPUT_PER_HOUR"
	mbpCodeNoOfProcess       = "NO_OF_PROCESS"
)

// TransitionWithAutoGen performs the same work as Transition, then — only when toState is
// StatusValidated and entity's cost product has not already been generated — auto-generates the
// linked cost_product_master/cost_route_*/CAPP/CPP rows per design addendum §10.2. All writes
// (transition + auto-gen) commit or roll back together.
func (r *MBHeadRepository) TransitionWithAutoGen(ctx context.Context, id uuid.UUID, fromState, toState string, currentVersion int32, stateReason, actorUserID string, params *mbhead.ParamSnapshot, entity *mbhead.Entity) error {
	return r.db.Transaction(ctx, func(tx *sql.Tx) error {
		if err := r.updateEntryStatusTx(ctx, tx, id, toState, currentVersion, stateReason, params); err != nil {
			return err
		}
		if err := r.insertWorkflowLogTx(ctx, tx, id, fromState, toState, actorUserID, stateReason, currentVersion); err != nil {
			return err
		}
		if toState != mbhead.StatusValidated {
			return nil
		}
		if err := r.compositionRepo.SnapshotVersion(ctx, tx, id.String(), currentVersion, actorUserID); err != nil {
			return err
		}
		if entity.CostProductID() != 0 {
			return nil
		}
		return r.autoGenCostProduct(ctx, tx, id, currentVersion, actorUserID, entity)
	})
}

// autoGenCostProduct runs the 6-step auto-gen write sequence (design addendum §10.2) inside the
// caller's transaction.
func (r *MBHeadRepository) autoGenCostProduct(ctx context.Context, tx *sql.Tx, id uuid.UUID, version int32, actorUserID string, entity *mbhead.Entity) error {
	typeID, err := mbResolveCostProductTypeID(ctx, tx)
	if err != nil {
		return err
	}
	productSysID, err := mbInsertCostProductMaster(ctx, tx, typeID, entity, actorUserID)
	if err != nil {
		return err
	}
	headID, err := mbInsertRouteHead(ctx, tx, productSysID, actorUserID)
	if err != nil {
		return err
	}
	seqID, err := mbInsertRouteSeq(ctx, tx, headID, productSysID, actorUserID)
	if err != nil {
		return err
	}
	rows, err := r.compositionRepo.ListVersionByMbhIDAndVersion(ctx, tx, id.String(), version)
	if err != nil {
		return err
	}
	if err := mbInsertRouteRMs(ctx, tx, seqID, productSysID, rows, actorUserID); err != nil {
		return err
	}
	if err := mbFreezeCostParams(ctx, tx, productSysID, entity, actorUserID); err != nil {
		return err
	}
	return mbWriteBackCostProduct(ctx, tx, id, productSysID, actorUserID)
}

func mbResolveCostProductTypeID(ctx context.Context, tx *sql.Tx) (int32, error) {
	const q = `SELECT cpt_type_id FROM cost_product_type WHERE cpt_type_code = $1 AND cpt_is_active = TRUE`
	var typeID int32
	if err := tx.QueryRowContext(ctx, q, mbCostProductTypeCode).Scan(&typeID); err != nil {
		return 0, fmt.Errorf("mb_autogen: resolve cost_product_type: %w", err)
	}
	return typeID, nil
}

func mbInsertCostProductMaster(ctx context.Context, tx *sql.Tx, typeID int32, entity *mbhead.Entity, actorUserID string) (int64, error) {
	const codeQ = `SELECT generate_cost_product_code($1)`
	var code string
	if err := tx.QueryRowContext(ctx, codeQ, typeID).Scan(&code); err != nil {
		return 0, fmt.Errorf("mb_autogen: generate cost product code: %w", err)
	}

	const insertQ = `
		INSERT INTO cost_product_master
			(cpm_product_code, cpm_product_type_id, cpm_product_name, cpm_source, cpm_is_locked,
			 cpm_created_by, cpm_updated_by)
		VALUES ($1, $2, $3, $4, TRUE, $5, $5)
		RETURNING cpm_product_sys_id`
	var productSysID int64
	err := tx.QueryRowContext(ctx, insertQ, code, typeID, entity.MBCosting(), mbCostProductSource, actorUserID).Scan(&productSysID)
	if err != nil {
		return 0, fmt.Errorf("mb_autogen: insert cost_product_master: %w", err)
	}
	return productSysID, nil
}

func mbInsertRouteHead(ctx context.Context, tx *sql.Tx, productSysID int64, actorUserID string) (int64, error) {
	const q = `
		INSERT INTO cost_route_head (crh_product_sys_id, crh_routing_status, crh_version, crh_created_by, crh_updated_by)
		VALUES ($1, $2, 1, $3, $3)
		RETURNING crh_head_id`
	var headID int64
	if err := tx.QueryRowContext(ctx, q, productSysID, costroute.StatusComplete, actorUserID).Scan(&headID); err != nil {
		return 0, fmt.Errorf("mb_autogen: insert cost_route_head: %w", err)
	}
	return headID, nil
}

func mbInsertRouteSeq(ctx context.Context, tx *sql.Tx, headID, productSysID int64, actorUserID string) (int64, error) {
	const q = `
		INSERT INTO cost_route_seq (crs_head_id, crs_product_sys_id, crs_route_level, crs_route_seq, crs_created_by, crs_updated_by)
		VALUES ($1, $2, 1, 1, $3, $3)
		RETURNING crs_seq_id`
	var seqID int64
	if err := tx.QueryRowContext(ctx, q, headID, productSysID, actorUserID).Scan(&seqID); err != nil {
		return 0, fmt.Errorf("mb_autogen: insert cost_route_seq: %w", err)
	}
	return seqID, nil
}

func mbInsertRouteRMs(ctx context.Context, tx *sql.Tx, seqID, parentProductSysID int64, rows []VersionRow, actorUserID string) error {
	const q = `
		INSERT INTO cost_route_rm
			(crm_seq_id, crm_parent_product_sys_id, crm_rm_product_sys_id, crm_rm_group_code,
			 crm_rm_type, crm_route_rm_ratio, crm_created_by, crm_updated_by)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $7)`
	for _, row := range rows {
		pct, err := strconv.ParseFloat(row.CompositionPct, 64)
		if err != nil {
			return fmt.Errorf("mb_autogen: parse composition pct: %w", err)
		}
		if pct == 0 {
			continue
		}
		ratio := pct / 100

		var rmType string
		var rmProductSysID *int64
		var rmGroupCode *string
		if row.SourceType == mbcomposition.SourceTypeMB {
			refProductSysID, resolveErr := mbResolveRefProductSysID(ctx, tx, row.MbRefMbhID)
			if resolveErr != nil {
				return resolveErr
			}
			rmType = costroute.RmTypeProduct
			rmProductSysID = &refProductSysID
		} else {
			rmType = costroute.RmTypeGroup
			groupCode := row.GroupCode
			rmGroupCode = &groupCode
		}

		if _, err := tx.ExecContext(ctx, q, seqID, parentProductSysID, rmProductSysID, rmGroupCode, rmType, ratio, actorUserID); err != nil {
			return fmt.Errorf("mb_autogen: insert cost_route_rm: %w", err)
		}
	}
	return nil
}

func mbResolveRefProductSysID(ctx context.Context, tx *sql.Tx, refMbhID string) (int64, error) {
	const q = `SELECT mbh_cost_product_id FROM mst_mb_head WHERE mbh_id = $1 AND deleted_at IS NULL`
	var productSysID int64
	if err := tx.QueryRowContext(ctx, q, refMbhID).Scan(&productSysID); err != nil {
		return 0, fmt.Errorf("mb_autogen: resolve nested MB cost product: %w", err)
	}
	return productSysID, nil
}

// mbOutputParamCodes are the 7 F_MB_* formulas' result_param_codes (migration 000452). They must
// be registered as CAPP rows (no CPP value — they are computed, not filled) so that LoadFormulas'
// cost_product_applicable_param join actually surfaces these formulas for the auto-generated MB
// cost product; without a CAPP row a formula is invisible to the calc engine regardless of it
// being seeded in mst_formula.
var mbOutputParamCodes = []string{
	"MB_RM_COST", "MB_WASTE_VAL", "MB_NET_PROD", "MB_FIXED_TOTAL",
	"MB_COST_OTHERS", "MB_CONV_COST", "MB_FINAL_COST",
}

// mbFreezeCostParams resolves the 11 mst_parameter IDs and upserts CAPP then CPP rows from the
// entity's already-frozen mbh_param_* values (never a runtime mst_mb_param lookup, except for the
// two picklist params whose option codes must be translated to numeric magnitudes here), then
// registers CAPP-only rows for the 7 F_MB_* formula output params so the calc engine picks them up.
func mbFreezeCostParams(ctx context.Context, tx *sql.Tx, productSysID int64, entity *mbhead.Entity, actorUserID string) error {
	throughputNumeric, err := mbResolveOptionNumericValue(ctx, tx, mbpCodeThroughputPerHour, entity.ParamThroughputPerHour())
	if err != nil {
		return err
	}
	noProcessNumeric, err := mbResolveOptionNumericValue(ctx, tx, mbpCodeNoOfProcess, entity.ParamNoOfProcess())
	if err != nil {
		return err
	}
	values := mbBuildParamValues(entity, throughputNumeric, noProcessNumeric)

	capp := make([]costproductparameter.CAPPUpsertInput, 0, len(values)+len(mbOutputParamCodes))
	cpp := make([]costproductparameter.CPPUpsertInput, 0, len(values))
	now := entity.CreatedAt()
	for _, v := range values {
		paramID, resolveErr := mbResolveParamID(ctx, tx, v.code)
		if resolveErr != nil {
			return resolveErr
		}
		if shapeErr := costproductparameter.EnsureValueShape(v.dataType, v.valueNumericStr, v.valueTextStr, v.valueFlag); shapeErr != nil {
			return fmt.Errorf("mb_autogen: param %s: %w", v.code, shapeErr)
		}
		capp = append(capp, costproductparameter.CAPPUpsertInput{ProductSysID: productSysID, ParamID: paramID, IsRequired: true})
		numeric, parseErr := mbParseOptionalFloat(v.valueNumericStr)
		if parseErr != nil {
			return parseErr
		}
		cpp = append(cpp, costproductparameter.CPPUpsertInput{
			ProductSysID: productSysID, ParamID: paramID,
			ValueNumeric: numeric, ValueText: v.valueTextStr, ValueFlag: v.valueFlag,
			FilledAt: now, FilledBy: actorUserID,
		})
	}
	for _, code := range mbOutputParamCodes {
		paramID, resolveErr := mbResolveParamID(ctx, tx, code)
		if resolveErr != nil {
			return resolveErr
		}
		capp = append(capp, costproductparameter.CAPPUpsertInput{ProductSysID: productSysID, ParamID: paramID, IsRequired: false})
	}

	if _, _, err := upsertCAPPBatch(ctx, tx, capp, actorUserID, now); err != nil {
		return fmt.Errorf("mb_autogen: upsert capp: %w", err)
	}
	if _, _, err := upsertCPPBatch(ctx, tx, cpp, actorUserID, now); err != nil {
		return fmt.Errorf("mb_autogen: upsert cpp: %w", err)
	}
	return nil
}

type mbParamValue struct {
	code            string
	dataType        string
	valueNumericStr *string
	valueTextStr    *string
	valueFlag       *bool
}

func mbBuildParamValues(entity *mbhead.Entity, throughputNumeric, noProcessNumeric *string) []mbParamValue {
	isBoughtout := entity.IsBoughtout()
	compositionVersion := strconv.FormatInt(int64(entity.CurrentVersion()), 10)
	machineFixedTotal := entity.MachineFixedTotal()
	if machineFixedTotal == nil {
		// No mbh_machine_id FK / machine picker exists yet (PRD Pattern C not wired) — 0 is the
		// placeholder snapshot until machine selection lands, not a validation failure.
		zero := "0"
		machineFixedTotal = &zero
	}

	return []mbParamValue{
		{code: paramMBWaste, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamWaste()},
		{code: paramMBQualityLoss, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamQualityLoss()},
		{code: paramMBEfficiency, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamEfficiency()},
		{code: paramMBDevExpense, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamDevExpense()},
		{code: paramMBPacking, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamPacking()},
		{code: paramMBProdPerDay, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamMBProdPerDay()},
		{code: paramMBThroughput, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: throughputNumeric},
		{code: paramMBNoProcess, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: noProcessNumeric},
		{code: paramIsBoughtout, dataType: string(costproductparameter.DataTypeBoolean), valueFlag: &isBoughtout},
		{code: paramMachineFixedTotal, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: machineFixedTotal},
		{code: paramCompositionVer, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: &compositionVersion},
	}
}

// mbResolveOptionNumericValue translates a frozen mst_mb_param picklist option code (e.g.
// throughput_per_hour="B") into its mst_mb_param_option.mbpo_numeric_value magnitude, which is
// what CPP must store for these two params (data_type NUMBER). Returns nil if code is empty.
func mbResolveOptionNumericValue(ctx context.Context, tx *sql.Tx, paramCode, optionCode string) (*string, error) {
	if optionCode == "" {
		return nil, nil //nolint:nilnil // absent selection is a legitimate "not set" signal, not an error
	}
	const q = `
		SELECT mbpo_numeric_value FROM mst_mb_param_option
		WHERE mbpo_mbp_code = $1 AND mbpo_code = $2 AND deleted_at IS NULL`
	var numeric float64
	if err := tx.QueryRowContext(ctx, q, paramCode, optionCode).Scan(&numeric); err != nil {
		return nil, fmt.Errorf("mb_autogen: resolve mst_mb_param_option %s/%s: %w", paramCode, optionCode, err)
	}
	v := strconv.FormatFloat(numeric, 'f', -1, 64)
	return &v, nil
}

func mbParseOptionalFloat(s *string) (*float64, error) {
	if s == nil {
		return nil, nil //nolint:nilnil // absent value is a legitimate "not set" signal, not an error
	}
	v, err := strconv.ParseFloat(*s, 64)
	if err != nil {
		return nil, fmt.Errorf("mb_autogen: parse numeric param: %w", err)
	}
	return &v, nil
}

func mbResolveParamID(ctx context.Context, tx *sql.Tx, code string) (uuid.UUID, error) {
	const q = `SELECT id FROM mst_parameter WHERE param_code = $1 AND deleted_at IS NULL`
	var id uuid.UUID
	if err := tx.QueryRowContext(ctx, q, code).Scan(&id); err != nil {
		return uuid.Nil, fmt.Errorf("mb_autogen: resolve mst_parameter %s: %w", code, err)
	}
	return id, nil
}

func mbWriteBackCostProduct(ctx context.Context, tx *sql.Tx, id uuid.UUID, productSysID int64, actorUserID string) error {
	const q = `
		UPDATE mst_mb_head
		SET mbh_cost_product_id = $2, mbh_cost_generated_at = NOW(), mbh_cost_generated_by = $3
		WHERE mbh_id = $1 AND deleted_at IS NULL`
	if _, err := tx.ExecContext(ctx, q, id, productSysID, actorUserID); err != nil {
		return fmt.Errorf("mb_autogen: write back cost product: %w", err)
	}
	return nil
}
