-- Revert this seed. Deletes the 76 mappings, then removes only the org-master rows
-- this seed created (created_by='seed') that have NO remaining child references --
-- so reused/shared rows (e.g. a section still used by another mapping) are left intact
-- and FK RESTRICT can never fire.
DELETE FROM mst_company_mapping WHERE created_by = 'seed' AND code IN (
    'MGTJKTGNRLGEN', 'MGTSLOCIMGEN', 'MGTSLOFINACNT', 'MGTSLOFINCOST', 'MGTSLOFINEXPT', 'MGTSLOFINMIS', 'MGTSLOFINPAY', 'MGTSLOFINREC', 'MGTSLOFINTAX', 'MGTSLOHRMATT', 'MGTSLOHRMDRV', 'MGTSLOHRMGEN', 'MGTSLOHRMLGL', 'MGTSLOHRMRECRUT', 'MGTSLOHRMSCRTY', 'MGTSLOHRMTRAIN', 'MGTSLOHRMTRNSPT', 'MGTSLOHRMWLFR', 'MGTSLOHSSSCRTY', 'MGTSLOHSSSFTY', 'MGTSLOITHARD', 'MGTSLOITHWHARD', 'MGTSLOITSOFT', 'MGTSLOITSSOFT', 'MGTSLOMBGEN', 'MGTSLOMCDES', 'MGTSLOMCEXPT', 'MGTSLOMCIMP', 'MGTSLOMCPURCH', 'MGTSLOMCSTRS', 'MGTSLOMCWHS', 'MGTSLOPPCEXPT', 'MGTSLOPPCPPC', 'MGTSLORNDEXPT', 'MGTSLORNDRND', 'MGTSLOSPBAEXPT', 'MGTSLOSPGBO', 'MGTSLOSPGEXPT', 'MGTSLOSPGGEN', 'MGTSLOSPGMECH', 'MGTSLOSPGMELT', 'MGTSLOSPGPACK', 'MGTSLOSPGPC', 'MGTSLOSPGPOP', 'MGTSLOSPGPPRTB', 'MGTSLOSPGPROD', 'MGTSLOSPGTAKE', 'MGTSLOTPMCCVL', 'MGTSLOTPMEELECT', 'MGTSLOTPMEEXPT', 'MGTSLOTPMGGEN', 'MGTSLOTPMUCVL', 'MGTSLOTPMUEXPT', 'MGTSLOTPMUUTIL', 'MGTSLOTQMEXPT', 'MGTSLOTQMGEN', 'MGTSLOTQMLABCHEM', 'MGTSLOTQMLABTEKS', 'MGTSLOTQMPC', 'MGTSLOTQMQA', 'MGTSLOTWTCOLKIT', 'MGTSLOTWTEXPT', 'MGTSLOTWTGEN', 'MGTSLOTWTMECH', 'MGTSLOTWTPACK', 'MGTSLOTWTPC', 'MGTSLOTWTPPC', 'MGTSLOTWTPROD', 'MGTSLOTWTRND', 'MGTSLOTXTEXPT', 'MGTSLOTXTGEN', 'MGTSLOTXTMECH', 'MGTSLOTXTPACK', 'MGTSLOTXTPPC', 'MGTSLOTXTPROD', 'MGTSLOUNHEXPT'
);
DELETE FROM mst_section s WHERE s.created_by = 'seed' AND s.section_code IN (
    'CIMGEN', 'FINACNT', 'FINCOST', 'FINEXPT', 'FINMIS', 'FINPAY', 'FINREC', 'FINTAX', 'GNRLGEN', 'HRMATT', 'HRMDRV', 'HRMGEN', 'HRMLGL', 'HRMRECRUT', 'HRMSCRTY', 'HRMTRAIN', 'HRMTRNSPT', 'HRMWLFR', 'HSSSCRTY', 'HSSSFTY', 'ITHARD', 'ITHWHARD', 'ITSOFT', 'ITSSOFT', 'MBGEN', 'MCDES', 'MCEXPT', 'MCIMP', 'MCPURCH', 'MCSTRS', 'MCWHS', 'PPCEXPT', 'PPCPPC', 'RNDEXPT', 'RNDRND', 'SPBAEXPT', 'SPGBO', 'SPGEXPT', 'SPGGEN', 'SPGMECH', 'SPGMELT', 'SPGPACK', 'SPGPC', 'SPGPOP', 'SPGPPRTB', 'SPGPROD', 'SPGTAKE', 'TPMCCVL', 'TPMEELECT', 'TPMEEXPT', 'TPMGGEN', 'TPMUCVL', 'TPMUEXPT', 'TPMUUTIL', 'TQMEXPT', 'TQMGEN', 'TQMLABCHEM', 'TQMLABTEKS', 'TQMPC', 'TQMQA', 'TWTCOLKIT', 'TWTEXPT', 'TWTGEN', 'TWTMECH', 'TWTPACK', 'TWTPC', 'TWTPPC', 'TWTPROD', 'TWTRND', 'TXTEXPT', 'TXTGEN', 'TXTMECH', 'TXTPACK', 'TXTPPC', 'TXTPROD', 'UNHEXPT'
)
  AND NOT EXISTS (SELECT 1 FROM mst_company_mapping m WHERE m.section_id = s.section_id);
DELETE FROM mst_department d WHERE d.created_by = 'seed' AND d.department_code IN ('CIM', 'FIN', 'GNRL', 'HRM', 'HSS', 'IT', 'ITHW', 'ITS', 'MB', 'MC', 'PPC', 'RND', 'SPBA', 'SPG', 'TPMC', 'TPME', 'TPMG', 'TPMU', 'TQM', 'TWT', 'TXT', 'UNH')
  AND NOT EXISTS (SELECT 1 FROM mst_section s WHERE s.department_id = d.department_id)
  AND NOT EXISTS (SELECT 1 FROM mst_company_mapping m WHERE m.department_id = d.department_id);
DELETE FROM mst_division dv WHERE dv.created_by = 'seed' AND dv.division_code IN ('SLO', 'JKT')
  AND NOT EXISTS (SELECT 1 FROM mst_department d WHERE d.division_id = dv.division_id)
  AND NOT EXISTS (SELECT 1 FROM mst_company_mapping m WHERE m.division_id = dv.division_id);
DELETE FROM mst_company c WHERE c.created_by = 'seed' AND c.company_code = 'MGT'
  AND NOT EXISTS (SELECT 1 FROM mst_division dv WHERE dv.company_id = c.company_id)
  AND NOT EXISTS (SELECT 1 FROM mst_company_mapping m WHERE m.company_id = c.company_id);
