DELETE FROM menu_permissions WHERE menu_id IN (
  SELECT menu_id FROM mst_menu WHERE menu_code IN (
    'FINANCE_MB_RECIPE','FINANCE_MB_PUSH_TO_HEAD','FINANCE_MB_LUSTURE','FINANCE_MB_PARAM'
  )
);
DELETE FROM mst_menu WHERE menu_code IN (
  'FINANCE_MB_RECIPE','FINANCE_MB_PUSH_TO_HEAD','FINANCE_MB_LUSTURE','FINANCE_MB_PARAM','FINANCE_MB_SECTION'
);
