-- Fix mst_parameter display_group and display_order to match reference Excel ordering.
-- Raw Material first (5-10), Machine (14-19), Yarn (20-25), Blend (26-38),
-- Packing (36-48), Production (49-61), Masterbatch & SP (63-74),
-- Special Treatment (75-80), Fixed Cost (82-91), Quality Loss (92-107),
-- Volume Bucket (108-122), Analysis (125-142), ungrouped (200+).
UPDATE mst_parameter SET
  display_group = CASE param_code
    WHEN 'RAW_MATERIAL' THEN 'Raw Material'
    WHEN 'RM_TYPE' THEN 'Raw Material'
    WHEN 'WASTE_PERC' THEN 'Raw Material'
    WHEN 'OPU' THEN 'Raw Material'
    WHEN 'RM_RATE' THEN 'Raw Material'
    WHEN 'RM_NORMS' THEN 'Raw Material'
    WHEN 'RM_LANDED_COST' THEN 'Raw Material'
    WHEN 'MC_NAME' THEN 'Machine'
    WHEN 'NO_OF_POSITION' THEN 'Machine'
    WHEN 'NO_OF_END' THEN 'Machine'
    WHEN 'MC_EFFICIENCY' THEN 'Machine'
    WHEN 'MC_SPEED' THEN 'Machine'
    WHEN 'TPM' THEN 'Machine'
    WHEN 'DENIER' THEN 'Yarn Specification'
    WHEN 'ACT_DENIER' THEN 'Yarn Specification'
    WHEN 'NO_OF_PLY' THEN 'Yarn Specification'
    WHEN 'NO_OF_FILAMENTS' THEN 'Yarn Specification'
    WHEN 'CROSS_SECTION' THEN 'Yarn Specification'
    WHEN 'INTERMINGLE' THEN 'Yarn Specification'
    WHEN 'AX_PERC' THEN 'Blend Composition'
    WHEN 'AE_PERC' THEN 'Blend Composition'
    WHEN 'A9_PERC' THEN 'Blend Composition'
    WHEN 'A_PERC' THEN 'Blend Composition'
    WHEN 'B_PERC' THEN 'Blend Composition'
    WHEN 'C_PERC' THEN 'Blend Composition'
    WHEN 'Y_TYPE' THEN 'Blend Composition'
    WHEN 'AX_WT' THEN 'Blend Composition'
    WHEN 'AE_WT' THEN 'Blend Composition'
    WHEN 'A9_WT' THEN 'Blend Composition'
    WHEN 'A_WT' THEN 'Blend Composition'
    WHEN 'B_WT' THEN 'Blend Composition'
    WHEN 'C_WT' THEN 'Blend Composition'
    WHEN 'NET_BOB_WT' THEN 'Packing'
    WHEN 'CAPTIVE_PACK_CODE' THEN 'Packing'
    WHEN 'CAPTIVE_NO_OF_BOB' THEN 'Packing'
    WHEN 'CAPTIVE_BOX_WT' THEN 'Packing'
    WHEN 'CAPTIVE_BOB_RATE' THEN 'Packing'
    WHEN 'CAPTIVE_BOX_RATE' THEN 'Packing'
    WHEN 'CAPTIVE_PACK_COST' THEN 'Packing'
    WHEN 'DELIVERY_PACK_CODE' THEN 'Packing'
    WHEN 'DELIVERY_NO_OF_BOB' THEN 'Packing'
    WHEN 'DELIVERY_BOX_WT' THEN 'Packing'
    WHEN 'DELIVERY_BOB_RATE' THEN 'Packing'
    WHEN 'DELIVERY_BOX_RATE' THEN 'Packing'
    WHEN 'DELIVERY_PACK_COST' THEN 'Packing'
    WHEN 'HEATSET_CODE' THEN 'Production'
    WHEN 'NO_OF_TROLLIES' THEN 'Production'
    WHEN 'NO_BOB_PER_TROLLIES' THEN 'Production'
    WHEN 'BATCH_WEIGHT' THEN 'Production'
    WHEN 'HEATSET_COST_PER_BATCH' THEN 'Production'
    WHEN 'HEATSET_COST_PER_KG' THEN 'Production'
    WHEN 'WASTE_LESS_MB_OPU' THEN 'Production'
    WHEN 'OIL_NAME' THEN 'Production'
    WHEN 'OIL_RATE' THEN 'Production'
    WHEN 'OIL_COST' THEN 'Production'
    WHEN 'MB_SP_CODE' THEN 'Masterbatch & SP'
    WHEN 'MB_SP_DYE' THEN 'Masterbatch & SP'
    WHEN 'MB_SP_DENIER' THEN 'Masterbatch & SP'
    WHEN 'MB_SP_FILAMENT' THEN 'Masterbatch & SP'
    WHEN 'MB_SP_CC' THEN 'Masterbatch & SP'
    WHEN 'MB_SP_DOZING' THEN 'Masterbatch & SP'
    WHEN 'CONV_FACTOR' THEN 'Masterbatch & SP'
    WHEN 'RP_CC' THEN 'Masterbatch & SP'
    WHEN 'RP_DOZING' THEN 'Masterbatch & SP'
    WHEN 'MB_RATE_MKT' THEN 'Masterbatch & SP'
    WHEN 'MB_COST_MKT' THEN 'Masterbatch & SP'
    WHEN 'INTERMINGLING' THEN 'Masterbatch & SP'
    WHEN 'SPECIAL_COST_FLAG' THEN 'Special Treatment'
    WHEN 'SPECIAL_COST_1' THEN 'Special Treatment'
    WHEN 'SPECIAL_COST_2' THEN 'Special Treatment'
    WHEN 'STEAM_COST_CNG' THEN 'Special Treatment'
    WHEN 'SOFTNER_COST' THEN 'Special Treatment'
    WHEN 'WASHING_COST' THEN 'Special Treatment'
    WHEN 'NET_PRODUCTION' THEN 'Fixed Cost'
    WHEN 'POWER_PER_DAY' THEN 'Fixed Cost'
    WHEN 'MANPOWER_PER_DAY' THEN 'Fixed Cost'
    WHEN 'OVERHEAD_PER_HEAD' THEN 'Fixed Cost'
    WHEN 'SPARESCOST_PER_DAY' THEN 'Fixed Cost'
    WHEN 'POWER_PER_KG' THEN 'Fixed Cost'
    WHEN 'MANPOWER_PER_KG' THEN 'Fixed Cost'
    WHEN 'OVERHEAD_PER_KG' THEN 'Fixed Cost'
    WHEN 'SPARESCOST_PER_KG' THEN 'Fixed Cost'
    WHEN 'TOTAL_FIXEDCOST_PER_KG' THEN 'Fixed Cost'
    WHEN 'ONLY_CONV_CAP_PACK_EXCL_MB' THEN 'Quality Loss'
    WHEN 'ONLY_CONV_DEL_PACK_EXCL_MB' THEN 'Quality Loss'
    WHEN 'CAPTIVE_COST_BEFORE_QLOSS' THEN 'Quality Loss'
    WHEN 'DELIVERY_COST_BEFORE_QLOSS' THEN 'Quality Loss'
    WHEN 'STD_VALUE_LOSS' THEN 'Quality Loss'
    WHEN 'VALUE_LOSS' THEN 'Quality Loss'
    WHEN 'NON_STD_SPECIAL_PROD' THEN 'Quality Loss'
    WHEN 'BC_SPECIAL_PROD' THEN 'Quality Loss'
    WHEN 'NON_STD_VALUE_LOSS' THEN 'Quality Loss'
    WHEN 'BC_VAL_LOSS_CAPTIVE' THEN 'Quality Loss'
    WHEN 'BC_VAL_LOSS_DELIVERY' THEN 'Quality Loss'
    WHEN 'QLTY_LOSS_CAPTIVE_COST' THEN 'Quality Loss'
    WHEN 'QLTY_LOSS_DELIVERY_COST' THEN 'Quality Loss'
    WHEN 'CAPTIVE_COST_QLTY_LOSS' THEN 'Quality Loss'
    WHEN 'DELIVERY_COST_QLTY_LOSS' THEN 'Quality Loss'
    WHEN 'CHANGE_OVER_QLTY_LOSS' THEN 'Quality Loss'
    WHEN 'VOLUME_BUCKET_1_QTY' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_2_QTY' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_3_QTY' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_4_QTY' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_5_QTY' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_1_LOSS' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_2_LOSS' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_3_LOSS' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_4_LOSS' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_5_LOSS' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_1_DEL_COST' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_2_DEL_COST' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_3_DEL_COST' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_4_DEL_COST' THEN 'Volume Bucket'
    WHEN 'VOLUME_BUCKET_5_DEL_COST' THEN 'Volume Bucket'
    WHEN 'OIL_GAIN' THEN 'Analysis'
    WHEN 'DOZING_ADJUST' THEN 'Analysis'
    WHEN 'DELIVERY_COST_BEFORE_QLOSS_ADD_PER' THEN 'Analysis'
    WHEN 'DELIVERY_COST_BEFORE_QLOSS_BEFORE_PROCESS' THEN 'Analysis'
    WHEN 'DELIVERY_COST_BEFORE_QLOSS_ADDITION' THEN 'Analysis'
    WHEN 'NON_STD_BC_SP' THEN 'Analysis'
    WHEN 'ADD_NON_STD_BC_LOSS' THEN 'Analysis'
    WHEN 'R_AX' THEN 'Analysis'
    WHEN 'R_AE_A9_A' THEN 'Analysis'
    WHEN 'R_BC' THEN 'Analysis'
    WHEN 'R_NON_STD_SP' THEN 'Analysis'
    WHEN 'R_NON_STD_DIFF' THEN 'Analysis'
    WHEN 'BC_SP' THEN 'Analysis'
    WHEN 'R_NON_STD_LOSS' THEN 'Analysis'
    WHEN 'R_BC_LOSS' THEN 'Analysis'
    WHEN 'ADDITIONAL_VAL_LOSS' THEN 'Analysis'
    WHEN 'CAPTIVE_CONVERSION' THEN 'Analysis'
    WHEN 'DELIVERY_CONVERSION' THEN 'Analysis'
    WHEN 'MB_FLAG' THEN ''
    WHEN 'SOFTNER_COST_LOOKUP' THEN ''
    WHEN 'PRODUCT_INDEX' THEN ''
    WHEN 'CUSTOMER' THEN ''
    WHEN 'VALUATION' THEN ''
    WHEN 'COSTING_LINK' THEN ''
    WHEN 'ORION_LINK' THEN ''
    WHEN 'ORION_ITEM' THEN ''
    WHEN 'ITEM_NAME' THEN ''
    WHEN 'SHADE_CODE' THEN ''
    WHEN 'SHADE_NAME' THEN ''
    ELSE display_group
  END,
  display_order = CASE param_code
    WHEN 'RAW_MATERIAL' THEN 5
    WHEN 'RM_TYPE' THEN 5
    WHEN 'WASTE_PERC' THEN 6
    WHEN 'OPU' THEN 7
    WHEN 'RM_RATE' THEN 8
    WHEN 'RM_NORMS' THEN 9
    WHEN 'RM_LANDED_COST' THEN 10
    WHEN 'MC_NAME' THEN 14
    WHEN 'NO_OF_POSITION' THEN 15
    WHEN 'NO_OF_END' THEN 16
    WHEN 'MC_EFFICIENCY' THEN 17
    WHEN 'MC_SPEED' THEN 18
    WHEN 'TPM' THEN 19
    WHEN 'DENIER' THEN 20
    WHEN 'ACT_DENIER' THEN 21
    WHEN 'NO_OF_PLY' THEN 22
    WHEN 'NO_OF_FILAMENTS' THEN 23
    WHEN 'CROSS_SECTION' THEN 24
    WHEN 'INTERMINGLE' THEN 25
    WHEN 'AX_PERC' THEN 26
    WHEN 'AE_PERC' THEN 27
    WHEN 'A9_PERC' THEN 28
    WHEN 'A_PERC' THEN 29
    WHEN 'B_PERC' THEN 30
    WHEN 'C_PERC' THEN 31
    WHEN 'Y_TYPE' THEN 32
    WHEN 'AX_WT' THEN 33
    WHEN 'AE_WT' THEN 34
    WHEN 'A9_WT' THEN 35
    WHEN 'A_WT' THEN 36
    WHEN 'B_WT' THEN 37
    WHEN 'C_WT' THEN 38
    WHEN 'NET_BOB_WT' THEN 39
    WHEN 'CAPTIVE_PACK_CODE' THEN 40
    WHEN 'CAPTIVE_NO_OF_BOB' THEN 41
    WHEN 'CAPTIVE_BOX_WT' THEN 42
    WHEN 'CAPTIVE_BOB_RATE' THEN 43
    WHEN 'CAPTIVE_BOX_RATE' THEN 44
    WHEN 'CAPTIVE_PACK_COST' THEN 45
    WHEN 'DELIVERY_PACK_CODE' THEN 46
    WHEN 'DELIVERY_NO_OF_BOB' THEN 47
    WHEN 'DELIVERY_BOX_WT' THEN 48
    WHEN 'DELIVERY_BOB_RATE' THEN 49
    WHEN 'DELIVERY_BOX_RATE' THEN 50
    WHEN 'DELIVERY_PACK_COST' THEN 51
    WHEN 'HEATSET_CODE' THEN 52
    WHEN 'NO_OF_TROLLIES' THEN 53
    WHEN 'NO_BOB_PER_TROLLIES' THEN 54
    WHEN 'BATCH_WEIGHT' THEN 55
    WHEN 'HEATSET_COST_PER_BATCH' THEN 56
    WHEN 'HEATSET_COST_PER_KG' THEN 57
    WHEN 'WASTE_LESS_MB_OPU' THEN 58
    WHEN 'OIL_NAME' THEN 59
    WHEN 'OIL_RATE' THEN 60
    WHEN 'OIL_COST' THEN 61
    WHEN 'MB_SP_CODE' THEN 63
    WHEN 'MB_SP_DYE' THEN 64
    WHEN 'MB_SP_DENIER' THEN 65
    WHEN 'MB_SP_FILAMENT' THEN 66
    WHEN 'MB_SP_CC' THEN 67
    WHEN 'MB_SP_DOZING' THEN 68
    WHEN 'CONV_FACTOR' THEN 69
    WHEN 'RP_CC' THEN 70
    WHEN 'RP_DOZING' THEN 71
    WHEN 'MB_RATE_MKT' THEN 72
    WHEN 'MB_COST_MKT' THEN 73
    WHEN 'INTERMINGLING' THEN 74
    WHEN 'SPECIAL_COST_FLAG' THEN 75
    WHEN 'SPECIAL_COST_1' THEN 76
    WHEN 'SPECIAL_COST_2' THEN 77
    WHEN 'STEAM_COST_CNG' THEN 78
    WHEN 'SOFTNER_COST' THEN 79
    WHEN 'WASHING_COST' THEN 80
    WHEN 'NET_PRODUCTION' THEN 82
    WHEN 'POWER_PER_DAY' THEN 83
    WHEN 'MANPOWER_PER_DAY' THEN 84
    WHEN 'OVERHEAD_PER_HEAD' THEN 85
    WHEN 'SPARESCOST_PER_DAY' THEN 86
    WHEN 'POWER_PER_KG' THEN 87
    WHEN 'MANPOWER_PER_KG' THEN 88
    WHEN 'OVERHEAD_PER_KG' THEN 89
    WHEN 'SPARESCOST_PER_KG' THEN 90
    WHEN 'TOTAL_FIXEDCOST_PER_KG' THEN 91
    WHEN 'ONLY_CONV_CAP_PACK_EXCL_MB' THEN 92
    WHEN 'ONLY_CONV_DEL_PACK_EXCL_MB' THEN 93
    WHEN 'CAPTIVE_COST_BEFORE_QLOSS' THEN 94
    WHEN 'DELIVERY_COST_BEFORE_QLOSS' THEN 95
    WHEN 'STD_VALUE_LOSS' THEN 96
    WHEN 'VALUE_LOSS' THEN 97
    WHEN 'NON_STD_SPECIAL_PROD' THEN 98
    WHEN 'BC_SPECIAL_PROD' THEN 99
    WHEN 'NON_STD_VALUE_LOSS' THEN 100
    WHEN 'BC_VAL_LOSS_CAPTIVE' THEN 101
    WHEN 'BC_VAL_LOSS_DELIVERY' THEN 102
    WHEN 'QLTY_LOSS_CAPTIVE_COST' THEN 103
    WHEN 'QLTY_LOSS_DELIVERY_COST' THEN 104
    WHEN 'CAPTIVE_COST_QLTY_LOSS' THEN 105
    WHEN 'DELIVERY_COST_QLTY_LOSS' THEN 106
    WHEN 'CHANGE_OVER_QLTY_LOSS' THEN 107
    WHEN 'VOLUME_BUCKET_1_QTY' THEN 108
    WHEN 'VOLUME_BUCKET_2_QTY' THEN 109
    WHEN 'VOLUME_BUCKET_3_QTY' THEN 110
    WHEN 'VOLUME_BUCKET_4_QTY' THEN 111
    WHEN 'VOLUME_BUCKET_5_QTY' THEN 112
    WHEN 'VOLUME_BUCKET_1_LOSS' THEN 113
    WHEN 'VOLUME_BUCKET_2_LOSS' THEN 114
    WHEN 'VOLUME_BUCKET_3_LOSS' THEN 115
    WHEN 'VOLUME_BUCKET_4_LOSS' THEN 116
    WHEN 'VOLUME_BUCKET_5_LOSS' THEN 117
    WHEN 'VOLUME_BUCKET_1_DEL_COST' THEN 118
    WHEN 'VOLUME_BUCKET_2_DEL_COST' THEN 119
    WHEN 'VOLUME_BUCKET_3_DEL_COST' THEN 120
    WHEN 'VOLUME_BUCKET_4_DEL_COST' THEN 121
    WHEN 'VOLUME_BUCKET_5_DEL_COST' THEN 122
    WHEN 'OIL_GAIN' THEN 125
    WHEN 'DOZING_ADJUST' THEN 126
    WHEN 'DELIVERY_COST_BEFORE_QLOSS_ADD_PER' THEN 127
    WHEN 'DELIVERY_COST_BEFORE_QLOSS_BEFORE_PROCESS' THEN 128
    WHEN 'DELIVERY_COST_BEFORE_QLOSS_ADDITION' THEN 129
    WHEN 'NON_STD_BC_SP' THEN 130
    WHEN 'ADD_NON_STD_BC_LOSS' THEN 131
    WHEN 'R_AX' THEN 132
    WHEN 'R_AE_A9_A' THEN 133
    WHEN 'R_BC' THEN 134
    WHEN 'R_NON_STD_SP' THEN 135
    WHEN 'R_NON_STD_DIFF' THEN 136
    WHEN 'BC_SP' THEN 137
    WHEN 'R_NON_STD_LOSS' THEN 138
    WHEN 'R_BC_LOSS' THEN 139
    WHEN 'ADDITIONAL_VAL_LOSS' THEN 140
    WHEN 'CAPTIVE_CONVERSION' THEN 141
    WHEN 'DELIVERY_CONVERSION' THEN 142
    WHEN 'MB_FLAG' THEN 200
    WHEN 'SOFTNER_COST_LOOKUP' THEN 201
    WHEN 'PRODUCT_INDEX' THEN 202
    WHEN 'CUSTOMER' THEN 203
    WHEN 'VALUATION' THEN 204
    WHEN 'COSTING_LINK' THEN 205
    WHEN 'ORION_LINK' THEN 206
    WHEN 'ORION_ITEM' THEN 207
    WHEN 'ITEM_NAME' THEN 208
    WHEN 'SHADE_CODE' THEN 209
    WHEN 'SHADE_NAME' THEN 210
    ELSE display_order
  END
WHERE param_code IN (
  'RAW_MATERIAL','RM_TYPE','WASTE_PERC','OPU','RM_RATE','RM_NORMS','RM_LANDED_COST',
  'MC_NAME','NO_OF_POSITION','NO_OF_END','MC_EFFICIENCY','MC_SPEED','TPM',
  'DENIER','ACT_DENIER','NO_OF_PLY','NO_OF_FILAMENTS','CROSS_SECTION','INTERMINGLE',
  'AX_PERC','AE_PERC','A9_PERC','A_PERC','B_PERC','C_PERC','Y_TYPE',
  'AX_WT','AE_WT','A9_WT','A_WT','B_WT','C_WT',
  'NET_BOB_WT','CAPTIVE_PACK_CODE','CAPTIVE_NO_OF_BOB','CAPTIVE_BOX_WT',
  'CAPTIVE_BOB_RATE','CAPTIVE_BOX_RATE','CAPTIVE_PACK_COST',
  'DELIVERY_PACK_CODE','DELIVERY_NO_OF_BOB','DELIVERY_BOX_WT',
  'DELIVERY_BOB_RATE','DELIVERY_BOX_RATE','DELIVERY_PACK_COST',
  'HEATSET_CODE','NO_OF_TROLLIES','NO_BOB_PER_TROLLIES','BATCH_WEIGHT',
  'HEATSET_COST_PER_BATCH','HEATSET_COST_PER_KG','WASTE_LESS_MB_OPU',
  'OIL_NAME','OIL_RATE','OIL_COST',
  'MB_SP_CODE','MB_SP_DYE','MB_SP_DENIER','MB_SP_FILAMENT','MB_SP_CC','MB_SP_DOZING',
  'CONV_FACTOR','RP_CC','RP_DOZING','MB_RATE_MKT','MB_COST_MKT','INTERMINGLING',
  'SPECIAL_COST_FLAG','SPECIAL_COST_1','SPECIAL_COST_2','STEAM_COST_CNG','SOFTNER_COST','WASHING_COST',
  'NET_PRODUCTION','POWER_PER_DAY','MANPOWER_PER_DAY','OVERHEAD_PER_HEAD','SPARESCOST_PER_DAY',
  'POWER_PER_KG','MANPOWER_PER_KG','OVERHEAD_PER_KG','SPARESCOST_PER_KG','TOTAL_FIXEDCOST_PER_KG',
  'ONLY_CONV_CAP_PACK_EXCL_MB','ONLY_CONV_DEL_PACK_EXCL_MB',
  'CAPTIVE_COST_BEFORE_QLOSS','DELIVERY_COST_BEFORE_QLOSS',
  'STD_VALUE_LOSS','VALUE_LOSS','NON_STD_SPECIAL_PROD','BC_SPECIAL_PROD',
  'NON_STD_VALUE_LOSS','BC_VAL_LOSS_CAPTIVE','BC_VAL_LOSS_DELIVERY',
  'QLTY_LOSS_CAPTIVE_COST','QLTY_LOSS_DELIVERY_COST','CAPTIVE_COST_QLTY_LOSS',
  'DELIVERY_COST_QLTY_LOSS','CHANGE_OVER_QLTY_LOSS',
  'VOLUME_BUCKET_1_QTY','VOLUME_BUCKET_2_QTY','VOLUME_BUCKET_3_QTY',
  'VOLUME_BUCKET_4_QTY','VOLUME_BUCKET_5_QTY',
  'VOLUME_BUCKET_1_LOSS','VOLUME_BUCKET_2_LOSS','VOLUME_BUCKET_3_LOSS',
  'VOLUME_BUCKET_4_LOSS','VOLUME_BUCKET_5_LOSS',
  'VOLUME_BUCKET_1_DEL_COST','VOLUME_BUCKET_2_DEL_COST','VOLUME_BUCKET_3_DEL_COST',
  'VOLUME_BUCKET_4_DEL_COST','VOLUME_BUCKET_5_DEL_COST',
  'OIL_GAIN','DOZING_ADJUST',
  'DELIVERY_COST_BEFORE_QLOSS_ADD_PER','DELIVERY_COST_BEFORE_QLOSS_BEFORE_PROCESS',
  'DELIVERY_COST_BEFORE_QLOSS_ADDITION','NON_STD_BC_SP','ADD_NON_STD_BC_LOSS',
  'R_AX','R_AE_A9_A','R_BC','R_NON_STD_SP','R_NON_STD_DIFF','BC_SP',
  'R_NON_STD_LOSS','R_BC_LOSS','ADDITIONAL_VAL_LOSS','CAPTIVE_CONVERSION','DELIVERY_CONVERSION',
  'MB_FLAG','SOFTNER_COST_LOOKUP','PRODUCT_INDEX','CUSTOMER','VALUATION',
  'COSTING_LINK','ORION_LINK','ORION_ITEM','ITEM_NAME','SHADE_CODE','SHADE_NAME'
);

-- Clear per-product display order overrides so all products inherit the master ordering above.
-- capp_display_order = NULL means "use mst_parameter.display_order" (COALESCE fallback).
UPDATE cost_product_applicable_param SET capp_display_order = NULL;
