DELETE FROM mst_parameter WHERE created_by = 'SYSTEM' AND param_code IN
    ('MB_WASTE','MB_QUALITY_LOSS','MB_EFFICIENCY','MB_DEV_EXPENSE','MB_PACKING',
     'MB_PROD_PER_DAY','MB_THROUGHPUT','MB_NO_PROCESS','IS_BOUGHTOUT',
     'MACHINE_MB_FIXED_TOTAL','MB_COMPOSITION_VERSION','MB_RM_COST','MB_WASTE_VAL',
     'MB_NET_PROD','MB_FIXED_TOTAL','MB_COST_OTHERS','MB_CONV_COST','MB_FINAL_COST');
DELETE FROM mst_mb_param_option WHERE mbpo_mbp_code IN ('THROUGHPUT_PER_HOUR','NO_OF_PROCESS');
DELETE FROM mst_mb_param WHERE mbp_created_by = 'SYSTEM';
