INSERT INTO mst_mb_lusture (mbl_code, mbl_display_name, mbl_full_description, mbl_category, mbl_display_order, mbl_created_by) VALUES
('SD','SD','Semi Dull','Standard',1,'SYSTEM'),
('DSD','DSD','Dope Dyed Colored Semi Dull','Dope Dyed',2,'SYSTEM'),
('OSD','OSD','Optical Semidull','Optical',3,'SYSTEM'),
('BRT','BRT','Bright','Standard',4,'SYSTEM'),
('FD','FD','Full Dull','Standard',5,'SYSTEM'),
('BSD','BSD','Black Semi Dull','Black',6,'SYSTEM'),
('BBRT','BBRT','Black Bright','Black',7,'SYSTEM'),
('BFD','BFD','Black Full Dull','Black',8,'SYSTEM'),
('SBSD','SBSD','Super Dyed Black Semi Dull','Black',9,'SYSTEM'),
('BSFR','BSDFR','Black Semi Dull Flame Retardant','Black + FR',10,'SYSTEM'),
('OBRT','OBRT','Optical Bright','Optical',11,'SYSTEM'),
('DBRT','DBRT','Dope Dyed Bright Colored','Dope Dyed',12,'SYSTEM'),
('DFD','DFD','Dope Dyed Full Dull','Dope Dyed',13,'SYSTEM'),
('DFSD','DFSD','Dope Dyed Colored Full Dull','Dope Dyed',14,'SYSTEM'),
('DSDA','DSD AS','Dope Dyed Colour Semidull Anti Static','Dope Dyed',15,'SYSTEM'),
('EDSD','EDSD','Eco Dope Dyed Colored Semi Dull','Eco',16,'SYSTEM'),
('ESD','ESD','Eco Semi Dull','Eco',17,'SYSTEM'),
('ERSD','ERSD','Eco Recycle Semi Dull','Eco Recycle',18,'SYSTEM'),
('RSD','RSD','Recycle Semi Dull','Recycle',19,'SYSTEM'),
('RFD','RFD','Recycle Full Dull','Recycle',20,'SYSTEM'),
('RBR','RBR','Recycle Bright','Recycle',21,'SYSTEM'),
('RDSD','RDSD','Recycle Dyed Semi Dull','Recycle',22,'SYSTEM'),
('RBSD','RBSD','Recycle Black Semi Dull','Recycle Black',23,'SYSTEM'),
('RBBR','RBBR','Recycle Black Bright','Recycle Black',24,'SYSTEM'),
('ROFD','ROFD','Recycle Optical Full Dull','Recycle Optical',25,'SYSTEM'),
('ROSD','ROSD','Recycle Optical Semidull','Recycle Optical',26,'SYSTEM'),
('RDFD','RDFD','Recycle Dope Dyed Full Dull','Recycle',27,'SYSTEM'),
('RSFR','RSDFR','Recycle Semi Dull Flame Retardant','Recycle + FR',28,'SYSTEM'),
('CSD','CSD','Cationic Semi Dull','Cationic',29,'SYSTEM'),
('CBRT','CBRT','Cationic Bright','Cationic',30,'SYSTEM'),
('CFSD','CFSD','Cationic Full Semi Dull','Cationic',31,'SYSTEM'),
('SCDP','SDCD PU','Semi Dull Cationic Dyeable Polyurethane','Cationic + PU',32,'SYSTEM'),
('SDCD','SDCD','Semi Dull Cationic Dyeable','Cationic',33,'SYSTEM'),
('PU','PU','Polyurethane','PU',34,'SYSTEM'),
('BSDP','BSD PU','BSD Polyurethane','PU + Black',35,'SYSTEM'),
('BSDB','BSD BPU','BSD Black Polyurethane','PU + Black',36,'SYSTEM'),
('BRTP','BRT PU','BRT Polyurethane','PU',37,'SYSTEM'),
('DSDP','DSD PU','DSD Polyurethane','PU + Dope Dyed',38,'SYSTEM'),
('FR','FR','Flame Retardant','FR',39,'SYSTEM'),
('SDFR','SDFR','Semi Dull Flame Retardant','FR',40,'SYSTEM'),
('SBR','SBR','Super Bright','Bright',41,'SYSTEM'),
('EBR','EBR','Extra Bright','Bright',42,'SYSTEM'),
('HBR','HBR','Health Bright','Specialty',43,'SYSTEM'),
('HSD','HSD','Health Semi Dull','Specialty',44,'SYSTEM'),
('HDSD','HDSD','Hank Dyeing Semi Dull','Specialty',45,'SYSTEM'),
('GSD','GSD','Glow Semi Dull','Specialty',46,'SYSTEM'),
('SSD','SSD','Super Dyed Semi Dull','Specialty',47,'SYSTEM'),
('MSD','MSD','Moisture Management Semi Dull','Specialty',48,'SYSTEM'),
('NSD','NSD','Nylon Semi Dull','Nylon',49,'SYSTEM'),
('PBSD','PBSD','PBT Semi Dull','PBT',50,'SYSTEM'),
('HTSD','HTSD','High Tenacity Semi Dull','Specialty',51,'SYSTEM'),
('SDBR','SDBR','Super Dyed Bright','Bright',52,'SYSTEM'),
('SPBR','SPBR','Space Bright','Space',53,'SYSTEM'),
('SPSD','SPSD','Space Semi Dull','Space',54,'SYSTEM')
ON CONFLICT (mbl_code) DO NOTHING;

INSERT INTO mst_mb_lusture (mbl_code, mbl_display_name, mbl_full_description, mbl_category, mbl_display_order, mbl_created_by) VALUES
('SPFB','SPFBR','Space Full Dull Bright','Space',55,'SYSTEM'),
('FBR','FBR','Full Dull Bright','Full Dull',56,'SYSTEM')
ON CONFLICT (mbl_code) DO NOTHING;
