// Package costproductmaster contains the CostProductMaster domain (PRD Phase B §7.4.1, CPM_).
package costproductmaster

import (
	"errors"
	"strings"
	"time"
)

var (
	// ErrNotFound is returned when a product master is not found.
	ErrNotFound = errors.New("cost product master not found")
	// ErrAlreadyExists is returned when product_code already exists (auto-code collision).
	ErrAlreadyExists = errors.New("cost product master code already exists")
	// ErrInvalidProductName is returned when product name fails validation.
	ErrInvalidProductName = errors.New("invalid product_name (must be 1..500 chars)")
	// ErrInvalidGradeCode is returned when grade_code is empty.
	ErrInvalidGradeCode = errors.New("invalid grade_code (must be 1..20 chars)")
	// ErrInactive is returned when attempting to modify a deactivated product.
	ErrInactive = errors.New("product master is inactive")
)

// CostProductMaster is the product identity aggregate.
type CostProductMaster struct {
	productSysID  int64
	productCode   string
	productTypeID int32
	productName   string
	shadeCode     string
	gradeCode     string
	description   string
	erpItemCode   string
	erpGradeCode1 string
	erpGradeCode2 string
	erpLinkedAt   *time.Time
	erpLinkedBy   string
	isActive      bool
	createdAt     time.Time
	createdBy     string
	updatedAt     time.Time
	updatedBy     string
}

// NewInput contains the create inputs (product_code is generated by DB).
type NewInput struct {
	ProductTypeID int32
	ProductName   string
	ShadeCode     string
	GradeCode     string
	Description   string
	ActorUserID   string
}

// New constructs a new CostProductMaster prior to insert. product_code and product_sys_id are assigned by repo.
func New(in NewInput) (*CostProductMaster, error) {
	name := strings.TrimSpace(in.ProductName)
	if name == "" || len(name) > 500 {
		return nil, ErrInvalidProductName
	}
	grade := strings.TrimSpace(in.GradeCode)
	if grade == "" {
		grade = "AX"
	}
	if len(grade) > 20 {
		return nil, ErrInvalidGradeCode
	}
	now := time.Now().UTC()
	return &CostProductMaster{
		productTypeID: in.ProductTypeID,
		productName:   name,
		shadeCode:     strings.TrimSpace(in.ShadeCode),
		gradeCode:     grade,
		description:   strings.TrimSpace(in.Description),
		isActive:      true,
		createdAt:     now,
		createdBy:     in.ActorUserID,
		updatedAt:     now,
		updatedBy:     in.ActorUserID,
	}, nil
}

// Reconstruct rebuilds an aggregate from persistence.
func Reconstruct(
	productSysID int64,
	productCode string,
	productTypeID int32,
	productName, shadeCode, gradeCode, description string,
	erpItemCode, erpGradeCode1, erpGradeCode2 string,
	erpLinkedAt *time.Time, erpLinkedBy string,
	isActive bool,
	createdAt time.Time, createdBy string,
	updatedAt time.Time, updatedBy string,
) *CostProductMaster {
	return &CostProductMaster{
		productSysID: productSysID, productCode: productCode, productTypeID: productTypeID,
		productName: productName, shadeCode: shadeCode, gradeCode: gradeCode, description: description,
		erpItemCode: erpItemCode, erpGradeCode1: erpGradeCode1, erpGradeCode2: erpGradeCode2,
		erpLinkedAt: erpLinkedAt, erpLinkedBy: erpLinkedBy,
		isActive:  isActive,
		createdAt: createdAt, createdBy: createdBy,
		updatedAt: updatedAt, updatedBy: updatedBy,
	}
}

// SetGeneratedCode is called by the repo after the DB returns the generated product_code + sys_id.
func (p *CostProductMaster) SetGeneratedCode(sysID int64, code string) {
	p.productSysID = sysID
	p.productCode = code
}

// Update mutates editable descriptive fields. product_type_id is immutable.
func (p *CostProductMaster) Update(productName, shadeCode, gradeCode, description, actor string) error {
	if !p.isActive {
		return ErrInactive
	}
	name := strings.TrimSpace(productName)
	if name == "" || len(name) > 500 {
		return ErrInvalidProductName
	}
	grade := strings.TrimSpace(gradeCode)
	if grade == "" {
		grade = p.gradeCode
	}
	if len(grade) > 20 {
		return ErrInvalidGradeCode
	}
	p.productName = name
	p.shadeCode = strings.TrimSpace(shadeCode)
	p.gradeCode = grade
	p.description = strings.TrimSpace(description)
	p.updatedAt = time.Now().UTC()
	p.updatedBy = actor
	return nil
}

// LinkErp sets/refreshes the ERP linkage. Empty erpItemCode unlinks.
func (p *CostProductMaster) LinkErp(erpItemCode, erpGradeCode1, erpGradeCode2, actor string) {
	now := time.Now().UTC()
	p.erpItemCode = strings.TrimSpace(erpItemCode)
	p.erpGradeCode1 = strings.TrimSpace(erpGradeCode1)
	p.erpGradeCode2 = strings.TrimSpace(erpGradeCode2)
	if p.erpItemCode == "" {
		p.erpLinkedAt = nil
		p.erpLinkedBy = ""
	} else {
		p.erpLinkedAt = &now
		p.erpLinkedBy = actor
	}
	p.updatedAt = now
	p.updatedBy = actor
}

// Deactivate flips the active flag off (soft-deactivate).
func (p *CostProductMaster) Deactivate(actor string) {
	if !p.isActive {
		return
	}
	p.isActive = false
	now := time.Now().UTC()
	p.updatedAt = now
	p.updatedBy = actor
}

// ProductSysID returns the product sys ID.
func (p *CostProductMaster) ProductSysID() int64 { return p.productSysID }

// ProductCode returns the product code.
func (p *CostProductMaster) ProductCode() string { return p.productCode }

// ProductTypeID returns the product type id.
func (p *CostProductMaster) ProductTypeID() int32 { return p.productTypeID }

// ProductName returns the product name.
func (p *CostProductMaster) ProductName() string { return p.productName }

// ShadeCode returns the shade code.
func (p *CostProductMaster) ShadeCode() string { return p.shadeCode }

// GradeCode returns the grade code.
func (p *CostProductMaster) GradeCode() string { return p.gradeCode }

// Description returns the description.
func (p *CostProductMaster) Description() string { return p.description }

// ErpItemCode returns the erp item code.
func (p *CostProductMaster) ErpItemCode() string { return p.erpItemCode }

// ErpGradeCode1 returns the erp grade code1.
func (p *CostProductMaster) ErpGradeCode1() string { return p.erpGradeCode1 }

// ErpGradeCode2 returns the erp grade code2.
func (p *CostProductMaster) ErpGradeCode2() string { return p.erpGradeCode2 }

// ErpLinkedAt returns the erp linked at.
func (p *CostProductMaster) ErpLinkedAt() *time.Time { return p.erpLinkedAt }

// ErpLinkedBy returns the erp linked by.
func (p *CostProductMaster) ErpLinkedBy() string { return p.erpLinkedBy }

// IsActive returns the is active.
func (p *CostProductMaster) IsActive() bool { return p.isActive }

// CreatedAt returns the created at.
func (p *CostProductMaster) CreatedAt() time.Time { return p.createdAt }

// CreatedBy returns the created by.
func (p *CostProductMaster) CreatedBy() string { return p.createdBy }

// UpdatedAt returns the updated at.
func (p *CostProductMaster) UpdatedAt() time.Time { return p.updatedAt }

// UpdatedBy returns the updated by.
func (p *CostProductMaster) UpdatedBy() string { return p.updatedBy }
